version: '3.7'

services:
    app:
        build:
            args:
                user: laravel
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: students-registrations
        container_name: students-registration-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - db
    db:
        container_name: students-registrations-db
        image: postgres:13-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./db.env
        ports:
            - 15432:5432

    nginx:
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        container_name: students-registration-nginx
        restart: unless-stopped
        ports:
            - 9000:80
        volumes:
            - ./:/var/www
        depends_on:
            - app
            - db
volumes:
    postgres_data:
